### ISSUE TITLE
CORS policy error

### ISSUE THREAD

**Issue by NicolasMICAUX** [Colaski/global-streaming-search#13]
```
Access to fetch at 'https://blooming-savannah-63408.herokuapp.com/https://apis.justwatch.com/content/titles/fr_FR/popular' from origin 'https://colaski.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
when using [https://colaski.github.io/global-streaming-search/](https://colaski.github.io/global-streaming-search/) from Chrome.

**Comment by Colaski** [comment]
The proxy service I was using no longer offers a free tier, so the website can only be ran through locally or in a docker image at the moment.

**Comment by erik9012** [comment]
You can disable Cors and enable Cors with a chrome extension. Maybe you dont need Cors then

**Comment by Colaski** [comment]
That was something that I considered, the problem is that unblocking CORS at a browser level is a security risk that I am not comfortable recommending.
