### ISSUE TITLE
404 for bundle.js and bundle.css

### ISSUE THREAD

**Issue by albino1** [Colaski/global-streaming-search#2]
Hey there,

I tried installing this today in both Windows and Linux.  In both cases I get a blank white page with only header information and some body tags with nothing inside of them in the html source.

Looking at the logs I get

```
  [16:28:48] 200 ─ 4.66ms ─ /
  [16:28:58] 404 ─ 0.24ms ─ /build/bundle.css
  [16:28:58] 404 ─ 0.39ms ─ /build/bundle.js
  [16:28:58] 200 ─ 2.14ms ─ /global.css
```

So both `bundle.css` and `bundle.js` appear to be missing.

Steps to reproduce are just the steps from your readme:

```
git clone https://github.com/Colaski/global-streaming-search.git
cd global-streaming-search
npm install
npm run start
> Global-Streaming-Search@1.0.0 start
> sirv public --no-clear --port 8000


  Your application is ready~! 🚀

  - Local:      http://localhost:8000
  - Network:    Add `--host` to expose

────────────────── LOGS ──────────────────

  [16:28:48] 200 ─ 4.66ms ─ /
  [16:28:58] 404 ─ 0.24ms ─ /build/bundle.css
  [16:28:58] 404 ─ 0.39ms ─ /build/bundle.js
  [16:28:58] 200 ─ 2.14ms ─ /global.css
```

**Comment by Colaski** [comment]
ah, the instructions do not include the build step. Must've accidentally removed the pre-built files.

running `npm run build` prior to the run start command should fix the issue, I'll update the readme to note.

**Comment by albino1** [comment]
Works now, thank you!

My understanding from when you originally launched this is it was using your personal JustWatch API key.  Should I be getting my own API key from JustWatch, and if so, is there anything I need to know about how to do that and where to change it within GSS?

**Comment by Colaski** [comment]
I have no account with JustWatch and no key, the details on the API can be found here, [https://github.com/Colaski/JustWatchAPITypeScript](https://github.com/Colaski/JustWatchAPITypeScript).

**Comment by albino1** [comment]
Got it.  Very cool piece of software, thank you for making it!
