### ISSUE TITLE
How to run on VPS

### ISSUE THREAD

**Issue by Retsu0907** [Colaski/global-streaming-search#4]
I love this service
But when I get the VPS to run, only the VPS's own localhost:8000 can be viewed
Other computers can not view with VPS IP :8000 connection

And then I see
Network: Add `--host` to expose
How do I set this up?

**Comment by Colaski** [comment]
[I just added a section to the README regarding this issue.](https://github.com/Colaski/global-streaming-search/blob/main/README.md#running-in-dockerserver)
