### ISSUE TITLE
Feature request: Add number of seasons per streaming service

### ISSUE THREAD

**Issue by GamerKingFaiz** [Colaski/global-streaming-search#5]
On the official website you can see the number of seasons per streaming service:
![image](https://user-images.githubusercontent.com/9065136/191591922-cdaa8248-aa6e-40b6-b619-27a11f41af0a.png)
This is helpful to be able to find which streaming service has all of a show's seasons.

In the API I see that this information is available,. For example, here is an object from the `offers` array.
```json
{
    "jw_entity_id": "ts85167",
    "type": "aggregated",
    "monetization_type": "flatrate",
    "provider_id": 15,
    "package_short_name": "hlu",
    "currency": "USD",
    "urls": {
        "standard_web": "https://www.hulu.com/watch/e03add94-3392-45a3-b036-034cb00ae9d0",
        "deeplink_rokuos": "launch/2285?contentID=e03add94-3392-45a3-b036-034cb00ae9d0"
    },
    "presentation_type": "hd",
    "element_count": 4,
    "new_element_count": 4,
    "country": "US"
}
```

You can see here that `element_count` is `4`, which indicates that US Hulu has 4 seasons of this show (What We Do in the Shadows).

Could you add this to the site please?

Here is a mockup I created, but feel free to design it as you see fit!
![image](https://user-images.githubusercontent.com/9065136/191593071-9ee09876-041d-4752-8732-6267bc1b7cf1.png)

**Comment by Colaski** [comment]
Added
